var data = new Date()
var dia =  data.getDate();

var audios=[
    /*0*/"",
    /*1*/"",
    /*2*/"",
    /*3*/"",
    /*4*/"",
    /*5*/"",
    /*6*/"",
    /*7*/"",
    /*8*/"",
    /*9*/"",
    /*10*/"",
    /*11*/"",
    /*12*/"",
    /*13*/"",
    /*14*/"",
    /*15*/"https://fustecdev-edu-app.github.io/audio/genesis5.mp3",
    /*16*/"",
    /*17*/"",
    /*18*/"",
    /*19*/"",
    /*20*/"",
    /*21*/"",
    /*22*/"",
    /*23*/"",
    /*24*/"",
    /*25*/"",
    /*26*/"",
    /*27*/"",
    /*28*/"",
    /*29*/"",
    /*30*/"",
    /*31*/"",
    /**/"",


]

var parasha15=[
   "PARASHÁ 1",
   "***************************************************************************************",
    /**/"  B'RESHIT ",
   /**/" (NO PRINCÍPIO) ",
   /**/"Dia 15 Mês 10",
   /**/"GENESIS CAPÍTULO 5",
   /**/"¹ Este é o livro das gerações de Adão. No dia em que Deus criou o homem, à semelhança de Deus o fez. ",
   /**/"² Homem e mulher os criou; e os abençoou e chamou o seu nome Adão, no dia em que foram criados. ",
   /**/"³ E Adão viveu cento e trinta anos, e gerou um filho à sua semelhança, conforme a sua imagem, e pôs-lhe o nome de Sete. ",
   /**/"⁴ E foram os dias de Adão, depois que gerou a Sete, oitocentos anos, e gerou filhos e filhas. ",
   /**/"⁵ E foram todos os dias que Adão viveu, novecentos e trinta anos, e morreu. ",
   /**/"⁶ E viveu Sete cento e cinco anos, e gerou a Enos. ",
   /**/"⁷ E viveu Sete, depois que gerou a Enos, oitocentos e sete anos, e gerou filhos e filhas. ",
   /**/"⁸ E foram todos os dias de Sete novecentos e doze anos, e morreu. ",
   /**/"⁹ E viveu Enos noventa anos, e gerou a Cainã. ",
   /**/"¹⁰ E viveu Enos, depois que gerou a Cainã, oitocentos e quinze anos, e gerou filhos e filhas. ",
   /**/"¹¹ E foram todos os dias de Enos novecentos e cinco anos, e morreu. ",
   /**/"¹² E viveu Cainã setenta anos, e gerou a Maalalel. ",
   /**/"¹³ E viveu Cainã, depois que gerou a Maalalel, oitocentos e quarenta anos, e gerou filhos e filhas. ",
   /**/"¹⁴ E foram todos os dias de Cainã novecentos e dez anos, e morreu. ",
   /**/"¹⁵ E viveu Maalalel sessenta e cinco anos, e gerou a Jerede. ",
   /**/"¹⁶ E viveu Maalalel, depois que gerou a Jerede, oitocentos e trinta anos, e gerou filhos e filhas. ",
   /**/"¹⁷ E foram todos os dias de Maalalel oitocentos e noventa e cinco anos, e morreu. ",
   /**/"¹⁸ E viveu Jerede cento e sessenta e dois anos, e gerou a Enoque. ",
   /**/"¹⁹ E viveu Jerede, depois que gerou a Enoque, oitocentos anos, e gerou filhos e filhas. ",
   /**/"²⁰ E foram todos os dias de Jerede novecentos e sessenta e dois anos, e morreu. ",
   /**/"²¹ E viveu Enoque sessenta e cinco anos, e gerou a Matusalém. ",
   /**/"²² E andou Enoque com Deus, depois que gerou a Matusalém, trezentos anos, e gerou filhos e filhas. ",
   /**/"²³ E foram todos os dias de Enoque trezentos e sessenta e cinco anos. ",
   /**/"²⁴ E andou Enoque com Deus; e não apareceu mais, porquanto Deus para si o tomou. ",
   /**/"²⁵ E viveu Matusalém cento e oitenta e sete anos, e gerou a Lameque. ",
   /**/"²⁶ E viveu Matusalém, depois que gerou a Lameque, setecentos e oitenta e dois anos, e gerou filhos e filhas. ",
   /**/"²⁷ E foram todos os dias de Matusalém novecentos e sessenta e nove anos, e morreu. ",
   /**/"²⁸ E viveu Lameque cento e oitenta e dois anos, e gerou um filho, ",
   /**/"²⁹ A quem chamou Noé, dizendo: Este nos consolará acerca de nossas obras e do trabalho de nossas mãos, por causa da terra que o Senhor amaldiçoou. ",
   /**/"³⁰ E viveu Lameque, depois que gerou a Noé, quinhentos e noventa e cinco anos, e gerou filhos e filhas. ",
   /**/"³¹ E foram todos os dias de Lameque setecentos e setenta e sete anos, e morreu. ",
   /**/"³² E era Noé da idade de quinhentos anos, e gerou Noé a Sem, Cão e Jafé. ",
   /**/"*****************************************************************************",
   /**/"GENESIS CAPÍTULO 6 V 1 ATE 8 ",
   /**/"¹ E aconteceu que, como os homens começaram a multiplicar-se sobre a face da terra, e lhes nasceram filhas, ",
   /**/"² Viram os filhos de Deus que as filhas dos homens eram formosas; e tomaram para si mulheres de todas as que escolheram. ",
   /**/"³ Então disse o Senhor: Não contenderá o meu Espírito para sempre com o homem; porque ele também é carne; porém os seus dias serão cento e vinte anos. ",
   /**/"⁴ Havia naqueles dias gigantes na terra; e também depois, quando os filhos de Deus entraram às filhas dos homens e delas geraram filhos; estes eram os valentes que houve na antiguidade, os homens de fama. ",
   /**/"⁵ E viu o Senhor que a maldade do homem se multiplicara sobre a terra e que toda a imaginação dos pensamentos de seu coração era só má continuamente. ",
   /**/"⁶ Então arrependeu-se o Senhor de haver feito o homem sobre a terra e pesou-lhe em seu coração. ",
   /**/"⁷ E disse o Senhor: Destruirei o homem que criei de sobre a face da terra, desde o homem até ao animal, até ao réptil, e até à ave dos céus; porque me arrependo de os haver feito. ",
   /**/"⁸ Noé, porém, achou graça aos olhos do Senhor. ",
   /**/"",
   /**/"",
   /**/"",

];
var parasha16=[
   /**/"PARASHÁ 1",
   /**/"*************************************************************************************",
   /**/"HAFTARÁ B'RESHIT",
   /**/"Dia 16 Mês 10",
   /**/"ISAÍAS CAPITULO 42 V 5 ",
   /**/" Assim diz Deus, o Senhor, que criou os céus, e os estendeu, e espraiou a terra, e a tudo quanto produz; que dá a respiração ao povo que nela está, e o espírito aos que andam nela. ",
   /**/"*****************************************************************************************",
   /**/"ISAÍAS CAPÍTULO 43 V 10",
   /**/" Vós sois as minhas testemunhas, diz o Senhor, e meu servo, a quem escolhi; para que o saibais, e me creiais, e entendais que eu sou o mesmo, e que antes de mim deus nenhum se formou, e depois de mim nenhum haverá. ",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",

];
var parasha18=[
   /**/"PARASHÁ 1",
   /**/"*************************************************************************************",
   /**/"ESCRITOS NAZARENOS",
   /**/"Dia 18 Mês 10",
   /**/"MATEUS CAPÍTULO 1 V 1 ATE 17 ",
   /**/"¹ Livro da geração de Jesus Cristo, filho de Davi, filho de Abraão. ",
   /**/"² Abraão gerou a Isaque; e Isaque gerou a Jacó; e Jacó gerou a Judá e a seus irmãos; ",
   /**/"³ E Judá gerou, de Tamar, a Perez e a Zerá; e Perez gerou a Esrom; e Esrom gerou a Arão; ",
   /**/"⁴ E Arão gerou a Aminadabe; e Aminadabe gerou a Naassom; e Naassom gerou a Salmom; ",
   /**/"⁵ E Salmom gerou, de Raabe, a Boaz; e Boaz gerou de Rute a Obede; e Obede gerou a Jessé; ",
   /**/"⁶ E Jessé gerou ao rei Davi; e o rei Davi gerou a Salomão da que foi mulher de Urias. ",
   /**/"⁷ E Salomão gerou a Roboão; e Roboão gerou a Abias; e Abias gerou a Asa; ",
   /**/"⁸ E Asa gerou a Josafá; e Josafá gerou a Jorão; e Jorão gerou a Uzias; ",
   /**/"⁹ E Uzias gerou a Jotão; e Jotão gerou a Acaz; e Acaz gerou a Ezequias; ",
   /**/"¹⁰ E Ezequias gerou a Manassés; e Manassés gerou a Amom; e Amom gerou a Josias; ",
   /**/"¹¹ E Josias gerou a Jeconias e a seus irmãos na deportação para Babilônia. ",
   /**/"¹² E, depois da deportação para a Babilônia, Jeconias gerou a Salatiel; e Salatiel gerou a Zorobabel; ",
   /**/"¹³ E Zorobabel gerou a Abiúde; e Abiúde gerou a Eliaquim; e Eliaquim gerou a Azor; ",
   /**/"¹⁴ E Azor gerou a Sadoque; e Sadoque gerou a Aquim; e Aquim gerou a Eliúde; ",
   /**/"¹⁵ E Eliúde gerou a Eleazar; e Eleazar gerou a Matã; e Matã gerou a Jacó; ",
   /**/"¹⁶ E Jacó gerou a José, marido de Maria, da qual nasceu JESUS, que se chama o Cristo. ",
   /**/"¹⁷ De sorte que todas as gerações, desde Abraão até Davi, são catorze gerações; e desde Davi até a deportação para a Babilônia, catorze gerações; e desde a deportação para a Babilônia até Cristo, catorze gerações. ",
   /**/"*************************************************************************************",
   /**/"MATEUS",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",

];

var parasha29=[
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",

];

var parasha=[]
var audio =[]

if (dia== 15) {
   parasha=parasha15
   audio= audios[dia]
}
if (dia== 16) {
   parasha=parasha16
   audio= audios[dia]
}



export {dia};
export {parasha};
export {audio};