var data = new Date()
var dia =  data.getDate();

var audios=[
    /*0*/"",
    /*1*/"",
    /*2*/"",
    /*3*/"",
    /*4*/"",
    /*5*/"",
    /*6*/"",
    /*7*/"",
    /*8*/"",
    /*9*/"",
    /*10*/"",
    /*11*/"",
    /*12*/"",
    /*13*/"",
    /*14*/"",
    /*15*/"",
    /*16*/"",
    /*17*/"",
    /*18*/"",
    /*19*/"",
    /*20*/"",
    /*21*/"",
    /*22*/"",
    /*23*/"",
    /*24*/"",
    /*25*/"",
    /*26*/"",
    /*27*/"",
    /*28*/"",
    /*29*/"",
    /*30*/"",
    /*31*/"",
    /**/"",


]

var parasha=[
   "Você e nosso convidado hoje as 13 hrs na comunidade B`ney Isra`el",
   "***************************************************************************************",
   /**/"Deuteronômio 31",
   /**/"¹ Depois foi Moisés, e falou estas palavras a todo o Israel, ",
   /**/"² E disse-lhes: Da idade de cento e vinte anos sou eu hoje; já não poderei mais sair e entrar; além disto o Senhor me disse: Não passarás o Jordão.  ",
   /**/" ³ O Senhor teu Deus passará adiante de ti; ele destruirá estas nações de diante de ti, para que as possuas; Josué passará adiante de ti, como o Senhor tem falado. ",
   /**/"⁴ E o Senhor lhes fará como fez a Siom e a Ogue, reis dos amorreus, e à sua terra, os quais destruiu. ",
   /**/"⁵ Quando, pois, o Senhor vo-los der diante de vós, então com eles fareis conforme a todo o mandamento que vos tenho ordenado. ",
   /**/"⁶ Esforçai-vos, e animai-vos; não temais, nem vos espanteis diante deles; porque o Senhor teu Deus é o que vai contigo; não te deixará nem te desamparará.  ",
   /**/"⁷ E chamou Moisés a Josué, e lhe disse aos olhos de todo o Israel: Esforça-te e anima-te; porque com este povo entrarás na terra que o Senhor jurou a teus pais lhes dar; e tu os farás herdá-la.  ",
   /**/"⁸ O Senhor, pois, é aquele que vai adiante de ti; ele será contigo, não te deixará, nem te desamparará; não temas, nem te espantes. ",
   /**/"⁹ E Moisés escreveu esta lei, e a deu aos sacerdotes, filhos de Levi, que levavam a arca da aliança do Senhor, e a todos os anciãos de Israel.  ",
   /**/"¹⁰ E ordenou-lhes Moisés, dizendo: Ao fim de cada sete anos, no tempo determinado do ano da remissão, na festa dos tabernáculos, ",
   /**/"¹¹ Quando todo o Israel vier a comparecer perante o Senhor teu Deus, no lugar que ele escolher, lerás esta lei diante de todo o Israel aos seus ouvidos. ",
   /**/"¹² Ajunta o povo, os homens e as mulheres, os meninos e os estrangeiros que estão dentro das tuas portas, para que ouçam e aprendam e temam ao Senhor vosso Deus, e tenham cuidado de fazer todas as palavras desta lei; ",
   /**/" ¹³ E que seus filhos, que não a souberem, ouçam e aprendam a temer ao Senhor vosso Deus, todos os dias que viverdes sobre a terra a qual ides, passando o Jordão, para a possuir. ",
   /**/"¹⁴ E disse o Senhor a Moisés: Eis que os teus dias são chegados, para que morras; chama a Josué, e apresentai-vos na tenda da congregação, para que eu lhe dê ordens. Assim foram Moisés e Josué, e se apresentaram na tenda da congregação. ",
   /**/"¹⁵ Então o Senhor apareceu na tenda, na coluna de nuvem; e a coluna de nuvem estava sobre a porta da tenda.  ",
   /**/"¹⁶ E disse o Senhor a Moisés: Eis que dormirás com teus pais; e este povo se levantará, e prostituir-se-á indo após os deuses estranhos na terra, para cujo meio vai, e me deixará, e anulará a minha aliança que tenho feito com ele. ",
   /**/"¹⁷ Assim se acenderá a minha ira naquele dia contra ele, e desampará-lo-ei, e esconderei o meu rosto dele, para que seja devorado; e tantos males e angústias o alcançarão, que dirá naquele dia: Não me alcançaram estes males, porque o meu Deus não está no meio de mim?  ",
   /**/"¹⁸ Esconderei, pois, totalmente o meu rosto naquele dia, por todo o mal que tiver feito, por se haverem tornado a outros deuses. ",
   /**/"¹⁹ Agora, pois, escrevei-vos este cântico, e ensinai-o aos filhos de Israel; ponde-o na sua boca, para que este cântico me seja por testemunha contra os filhos de Israel. ",
   /**/"²⁰ Porque introduzirei o meu povo na terra que jurei a seus pais, que mana leite e mel; e comerá, e se fartará, e se engordará; então se tornará a outros deuses, e os servirá, e me irritarão, e anularão a minha aliança. ",
   /**/"²¹ E será que, quando o alcançarem muitos males e angústias, então este cântico responderá contra ele por testemunha, pois não será esquecido da boca de sua descendência; porquanto conheço a sua imaginação, o que ele faz hoje, antes que o introduza na terra que tenho jurado. ",
   /**/"²² Assim Moisés escreveu este cântico naquele dia, e o ensinou aos filhos de Israel. ",
   /**/"²³ E ordenou a Josué, filho de Num, e disse: Esforça-te e anima-te; porque tu introduzirás os filhos de Israel na terra que lhes jurei; e eu serei contigo. ",
   /**/"²⁴ E aconteceu que, acabando Moisés de escrever num livro, todas as palavras desta lei, até se acabarem,  ",
   /**/"²⁵ Moisés deu ordem aos levitas, que levavam a arca da aliança do Senhor, dizendo: ",
   /**/"²⁶ Tomai este livro da lei, e ponde-o ao lado da arca da aliança do Senhor vosso Deus, para que ali esteja por testemunha contra ti. ",
   /**/"²⁷ Porque conheço a tua rebelião e a tua dura cerviz; eis que, vivendo eu ainda hoje convosco, rebeldes fostes contra o Senhor; e quanto mais depois da minha morte? ",
   /**/"²⁸ Ajuntai perante mim todos os anciãos das vossas tribos, e vossos oficiais, e aos seus ouvidos falarei estas palavras, e contra eles por testemunhas tomarei o céu e a terra. ",
   /**/"²⁹ Porque eu sei que depois da minha morte certamente vos corrompereis, e vos desviareis do caminho que vos ordenei; então este mal vos alcançará nos últimos dias, quando fizerdes mal aos olhos do Senhor, para o provocar à ira com a obra das vossas mãos. ",
   /**/"³⁰ Então Moisés falou as palavras deste cântico aos ouvidos de toda a congregação de Israel, até se acabarem. ",
   /**/"",
   /**/" ",
   /**/"",
   /**/"",
   /**/" ",
   /**/"**********************************************************************",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",

];

var parasha29=[
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",

];
let  audio = "https://s.bibliaonline.com.br/audio/play/1/acf/Deut/31/_/azure/en-US-OnyxTurboMultilingualNeural/audio.mp3"


export {dia};
export {parasha};
export {audio};