var data = new Date()
var dia =  data.getDate();

var audios=[
    /*0*/"",
    /*1*/"",
    /*2*/"",
    /*3*/"",
    /*4*/"",
    /*5*/"",
    /*6*/"",
    /*7*/"",
    /*8*/"",
    /*9*/"",
    /*10*/"",
    /*11*/"",
    /*12*/"",
    /*13*/"",
    /*14*/"",
    /*15*/"https://fustecdev-edu-app.github.io/audio/genesis5.mp3",
    /*16*/"",
    /*17*/"",
    /*18*/"",
    /*19*/"",
    /*20*/"",
    /*21*/"",
    /*22*/"",
    /*23*/"",
    /*24*/"",
    /*25*/"",
    /*26*/"",
    /*27*/"",
    /*28*/"",
    /*29*/"",
    /*30*/"",
    /*31*/"",
    /**/"",


]

var parasha15=[
   "PARASHÁ 1",
   "***************************************************************************************",
    /**/"  B'RESHIT ",
   /**/" (NO PRINCÍPIO) ",
   /**/"Dia 15 Mês 10",
   /**/"GENESIS CAPÍTULO 5",
   /**/"¹ Este é o livro das gerações de Adão. No dia em que Deus criou o homem, à semelhança de Deus o fez. ",
   /**/"² Homem e mulher os criou; e os abençoou e chamou o seu nome Adão, no dia em que foram criados. ",
   /**/"³ E Adão viveu cento e trinta anos, e gerou um filho à sua semelhança, conforme a sua imagem, e pôs-lhe o nome de Sete. ",
   /**/"⁴ E foram os dias de Adão, depois que gerou a Sete, oitocentos anos, e gerou filhos e filhas. ",
   /**/"⁵ E foram todos os dias que Adão viveu, novecentos e trinta anos, e morreu. ",
   /**/"⁶ E viveu Sete cento e cinco anos, e gerou a Enos. ",
   /**/"⁷ E viveu Sete, depois que gerou a Enos, oitocentos e sete anos, e gerou filhos e filhas. ",
   /**/"⁸ E foram todos os dias de Sete novecentos e doze anos, e morreu. ",
   /**/"⁹ E viveu Enos noventa anos, e gerou a Cainã. ",
   /**/"¹⁰ E viveu Enos, depois que gerou a Cainã, oitocentos e quinze anos, e gerou filhos e filhas. ",
   /**/"¹¹ E foram todos os dias de Enos novecentos e cinco anos, e morreu. ",
   /**/"¹² E viveu Cainã setenta anos, e gerou a Maalalel. ",
   /**/"¹³ E viveu Cainã, depois que gerou a Maalalel, oitocentos e quarenta anos, e gerou filhos e filhas. ",
   /**/"¹⁴ E foram todos os dias de Cainã novecentos e dez anos, e morreu. ",
   /**/"¹⁵ E viveu Maalalel sessenta e cinco anos, e gerou a Jerede. ",
   /**/"¹⁶ E viveu Maalalel, depois que gerou a Jerede, oitocentos e trinta anos, e gerou filhos e filhas. ",
   /**/"¹⁷ E foram todos os dias de Maalalel oitocentos e noventa e cinco anos, e morreu. ",
   /**/"¹⁸ E viveu Jerede cento e sessenta e dois anos, e gerou a Enoque. ",
   /**/"¹⁹ E viveu Jerede, depois que gerou a Enoque, oitocentos anos, e gerou filhos e filhas. ",
   /**/"²⁰ E foram todos os dias de Jerede novecentos e sessenta e dois anos, e morreu. ",
   /**/"²¹ E viveu Enoque sessenta e cinco anos, e gerou a Matusalém. ",
   /**/"²² E andou Enoque com Deus, depois que gerou a Matusalém, trezentos anos, e gerou filhos e filhas. ",
   /**/"²³ E foram todos os dias de Enoque trezentos e sessenta e cinco anos. ",
   /**/"²⁴ E andou Enoque com Deus; e não apareceu mais, porquanto Deus para si o tomou. ",
   /**/"²⁵ E viveu Matusalém cento e oitenta e sete anos, e gerou a Lameque. ",
   /**/"²⁶ E viveu Matusalém, depois que gerou a Lameque, setecentos e oitenta e dois anos, e gerou filhos e filhas. ",
   /**/"²⁷ E foram todos os dias de Matusalém novecentos e sessenta e nove anos, e morreu. ",
   /**/"²⁸ E viveu Lameque cento e oitenta e dois anos, e gerou um filho, ",
   /**/"²⁹ A quem chamou Noé, dizendo: Este nos consolará acerca de nossas obras e do trabalho de nossas mãos, por causa da terra que o Senhor amaldiçoou. ",
   /**/"³⁰ E viveu Lameque, depois que gerou a Noé, quinhentos e noventa e cinco anos, e gerou filhos e filhas. ",
   /**/"³¹ E foram todos os dias de Lameque setecentos e setenta e sete anos, e morreu. ",
   /**/"³² E era Noé da idade de quinhentos anos, e gerou Noé a Sem, Cão e Jafé. ",
   /**/"*****************************************************************************",
   /**/"GENESIS CAPÍTULO 6 V 1 ATE 8 ",
   /**/"¹ E aconteceu que, como os homens começaram a multiplicar-se sobre a face da terra, e lhes nasceram filhas, ",
   /**/"² Viram os filhos de Deus que as filhas dos homens eram formosas; e tomaram para si mulheres de todas as que escolheram. ",
   /**/"³ Então disse o Senhor: Não contenderá o meu Espírito para sempre com o homem; porque ele também é carne; porém os seus dias serão cento e vinte anos. ",
   /**/"⁴ Havia naqueles dias gigantes na terra; e também depois, quando os filhos de Deus entraram às filhas dos homens e delas geraram filhos; estes eram os valentes que houve na antiguidade, os homens de fama. ",
   /**/"⁵ E viu o Senhor que a maldade do homem se multiplicara sobre a terra e que toda a imaginação dos pensamentos de seu coração era só má continuamente. ",
   /**/"⁶ Então arrependeu-se o Senhor de haver feito o homem sobre a terra e pesou-lhe em seu coração. ",
   /**/"⁷ E disse o Senhor: Destruirei o homem que criei de sobre a face da terra, desde o homem até ao animal, até ao réptil, e até à ave dos céus; porque me arrependo de os haver feito. ",
   /**/"⁸ Noé, porém, achou graça aos olhos do Senhor. ",
   /**/"",
   /**/"",
   /**/"",

];
var parasha16=[
   /**/"PARASHÁ 1",
   /**/"*************************************************************************************",
   /**/"HAFTARÁ B'RESHIT",
   /**/"Dia 16 Mês 10",
   /**/"ISAÍAS CAPITULO 42 V 5 ",
   /**/" Assim diz Deus, o Senhor, que criou os céus, e os estendeu, e espraiou a terra, e a tudo quanto produz; que dá a respiração ao povo que nela está, e o espírito aos que andam nela. ",
   /**/"*****************************************************************************************",
   /**/"ISAÍAS CAPÍTULO 43 V 10",
   /**/" Vós sois as minhas testemunhas, diz o Senhor, e meu servo, a quem escolhi; para que o saibais, e me creiais, e entendais que eu sou o mesmo, e que antes de mim deus nenhum se formou, e depois de mim nenhum haverá. ",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",

];
var parasha17=[
   /**/"PARASHÁ 1",
   /**/"*************************************************************************************",
   /**/"ESCRITOS NAZARENOS",
   /**/"Dia 17 Mês 10",
   /**/"MATEUS CAPÍTULO 1 V 1 ATE 17 ",
   /**/"¹ Livro da geração de Jesus Cristo, filho de Davi, filho de Abraão. ",
   /**/"² Abraão gerou a Isaque; e Isaque gerou a Jacó; e Jacó gerou a Judá e a seus irmãos; ",
   /**/"³ E Judá gerou, de Tamar, a Perez e a Zerá; e Perez gerou a Esrom; e Esrom gerou a Arão; ",
   /**/"⁴ E Arão gerou a Aminadabe; e Aminadabe gerou a Naassom; e Naassom gerou a Salmom; ",
   /**/"⁵ E Salmom gerou, de Raabe, a Boaz; e Boaz gerou de Rute a Obede; e Obede gerou a Jessé; ",
   /**/"⁶ E Jessé gerou ao rei Davi; e o rei Davi gerou a Salomão da que foi mulher de Urias. ",
   /**/"⁷ E Salomão gerou a Roboão; e Roboão gerou a Abias; e Abias gerou a Asa; ",
   /**/"⁸ E Asa gerou a Josafá; e Josafá gerou a Jorão; e Jorão gerou a Uzias; ",
   /**/"⁹ E Uzias gerou a Jotão; e Jotão gerou a Acaz; e Acaz gerou a Ezequias; ",
   /**/"¹⁰ E Ezequias gerou a Manassés; e Manassés gerou a Amom; e Amom gerou a Josias; ",
   /**/"¹¹ E Josias gerou a Jeconias e a seus irmãos na deportação para Babilônia. ",
   /**/"¹² E, depois da deportação para a Babilônia, Jeconias gerou a Salatiel; e Salatiel gerou a Zorobabel; ",
   /**/"¹³ E Zorobabel gerou a Abiúde; e Abiúde gerou a Eliaquim; e Eliaquim gerou a Azor; ",
   /**/"¹⁴ E Azor gerou a Sadoque; e Sadoque gerou a Aquim; e Aquim gerou a Eliúde; ",
   /**/"¹⁵ E Eliúde gerou a Eleazar; e Eleazar gerou a Matã; e Matã gerou a Jacó; ",
   /**/"¹⁶ E Jacó gerou a José, marido de Maria, da qual nasceu JESUS, que se chama o Cristo. ",
   /**/"¹⁷ De sorte que todas as gerações, desde Abraão até Davi, são catorze gerações; e desde Davi até a deportação para a Babilônia, catorze gerações; e desde a deportação para a Babilônia até Cristo, catorze gerações. ",
   /**/"*************************************************************************************",
   /**/"MATEUS CAPÍTULO 19 V 3 ATE 9",
   /**/"³ Então chegaram a ele os fariseus, tentando-o, e dizendo-lhe: É lícito ao homem repudiar sua mulher por qualquer motivo? ",
   /**/"⁴ Ele, porém, respondendo, disse-lhes: Não tendes lido que aquele que os fez no princípio macho e fêmea os fez, ",
   /**/"⁵ E disse: Portanto, deixará o homem pai e mãe, e se unirá à sua mulher, e serão os dois em uma carne? ",
   /**/"⁶ Assim não são mais dois, mas uma só carne. Portanto, o que Deus ajuntou não o separe o homem. ",
   /**/"⁷ Disseram-lhe eles: Então, por que mandou Moisés dar-lhe carta de divórcio, e repudiá-la? ",
   /**/"⁸ Disse-lhes ele: Moisés, por causa da dureza dos vossos corações, vos permitiu repudiar vossas mulheres; mas ao princípio não foi assim. ",
   /**/"⁹ Eu vos digo, porém, que qualquer que repudiar sua mulher, não sendo por causa de fornicação, e casar com outra, comete adultério; e o que casar com a repudiada também comete adultério. ",
     /**/"*************************************************************************************",
   /**/"MARCOS CAPÍTULO 10 V 1 ATE 12",
   /**/"¹ E, levantando-se dali, foi para os termos da Judeia, além do Jordão, e a multidão outra vez se reuniu em torno dele; e tornou a ensiná-los, como tinha por costume. ",
   /**/"² E, aproximando-se dele os fariseus, perguntaram-lhe, tentando-o: É lícito ao homem repudiar sua mulher? ",
   /**/"³ Mas ele, respondendo, disse-lhes: Que vos mandou Moisés? ",
   /**/"⁴ E eles disseram: Moisés permitiu escrever carta de divórcio e repudiar. ",
   /**/"⁵ E Jesus, respondendo, disse-lhes: Pela dureza dos vossos corações vos deixou ele escrito esse mandamento; ",
   /**/"⁶ Porém, desde o princípio da criação, Deus os fez macho e fêmea. ",
   /**/"⁷ Por isso deixará o homem a seu pai e a sua mãe, e unir-se-á a sua mulher, ",
   /**/"⁸ E serão os dois uma carne; e assim já não serão dois, mas uma carne. ",
   /**/"⁹ Portanto, o que Deus ajuntou não o separe o homem. ",
   /**/"¹⁰ E em casa tornaram os discípulos a interrogá-lo acerca disto mesmo. ",
   /**/"¹¹ E ele lhes disse: Qualquer que deixar a sua mulher e casar com outra, adultera contra ela. ",
   /**/"¹² E, se a mulher deixar a seu marido, e casar com outro, adultera. ",
   /**/"*************************************************************************************",
   /**/"LUCAS 3 V 23 ATE 28",
   /**/"²³ E este mesmo Jesus estava como que começando os trinta anos, sendo (como se cuidava) filho de José, e José de Heli, ",
   /**/"²⁴ E Heli de Matã, e Matã de Levi, e Levi de Melqui, e Melqui de Janai, e Janai de José, ",
   /**/"²⁵ E José de Matatias, e Matatias de Amós, e Amós de Naum, e Naum de Esli, e Esli de Nagaí, ",
   /**/"²⁶ E Nagaí de Máate, e Máate de Matatias, e Matatias de Semei, e Semei de José, e José de Jodá, ",
   /**/"²⁷ E Jodá de Joanã, e Joanã de Resá, e Resá de Zorobabel, e Zorobabel de Salatiel, e Salatiel de Neri, ",
   /**/"²⁸ E Neri de Melqui, e Melqui de Adi, e Adi de Cosã, e Cosã de Elmadã, e Elmadã de Er, ",
    /**/"*************************************************************************************",
   /**/"APOCALIPSE 21 V 1 ATE 5",
   /**/"¹ E vi um novo céu, e uma nova terra. Porque já o primeiro céu e a primeira terra passaram, e o mar já não existe. ",
   /**/"² E eu, João, vi a santa cidade, a nova Jerusalém, que de Deus descia do céu, preparada como uma esposa adornada para o seu marido. ",
   /**/"³ E ouvi uma grande voz do céu, que dizia: Eis aqui o tabernáculo de Deus está com os homens, pois com eles habitará, e eles serão o seu povo, e o mesmo Deus estará com eles, e será o seu Deus. ",
   /**/"⁴ E Deus limpará de seus olhos toda a lágrima; e não haverá mais morte, nem pranto, nem clamor, nem dor; porque já as primeiras coisas são passadas. ",
   /**/"⁵ E o que estava assentado sobre o trono disse: Eis que faço novas todas as coisas. E disse-me: Escreve; porque estas palavras são verdadeiras e fiéis. ",
    /**/"*************************************************************************************",
   /**/"APOCALIPSE 22 V 1 ATE 5",
   /**/"¹ E mostrou-me o rio puro da água da vida, claro como cristal, que procedia do trono de Deus e do Cordeiro. ",
   /**/"² No meio da sua praça, e de um e de outro lado do rio, estava a árvore da vida, que produz doze frutos, dando seu fruto de mês em mês; e as folhas da árvore são para a saúde das nações. ",
   /**/"³ E ali nunca mais haverá maldição contra alguém; e nela estará o trono de Deus e do Cordeiro, e os seus servos o servirão. ",
   /**/"⁴ E verão o seu rosto, e nas suas testas estará o seu nome. ",
   /**/"⁵ E ali não haverá mais noite, e não necessitarão de lâmpada nem de luz do sol, porque o Senhor Deus os ilumina; e reinarão para todo o sempre. ",
  /**/"*************************************************************************************", 
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",

];

var parasha29=[
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",

];

var shabbat =[
    /**/"PARASHÁ 1",
   /**/"*************************************************************************************",
   /**/"SHABBAT SHALOM",
   /**/"Hoje Reunião na Comunidade B`ney Isra`el as 13 Hrs",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
   /**/"",
]

var parasha=[]
var audio =[]

if (dia== 17) {
   parasha=parasha17
   audio= audios[dia]
}
if (dia== 18) {
   parasha=shabbat
   audio= audios[dia]
}



export {dia};
export {parasha};
export {audio};